comments:
  EndOfSentenceFormat:
    active: true

complexity:
  CognitiveComplexMethod:
    active: true
  ComplexCondition:
    active: true
  ComplexInterface:
    active: true
  LargeClass:
    active: true
  LongMethod:
    active: true
  LongParameterList:
    active: true
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
  NestedBlockDepth:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
  TooManyFunctions:
    active: true

style:
  UnusedImports:
    active: true
  WildcardImport:
    active: true
    excludeImports:
      - "kotlin.math.*"
