comments:
  EndOfSentenceFormat:
    active: true

complexity:
  CognitiveComplexMethod:
    active: true

style:
  UnusedImports:
    active: true
  WildcardImport:
    active: true
    excludeImports:
      - "kotlin.math.*"
