comments:
  EndOfSentenceFormat:
    active: true

complexity:
  CognitiveComplexMethod:
    active: true
  ComplexCondition:
    active: true
  ComplexInterface:
    active: true
  LargeClass:
    active: true
  LongMethod:
    active: true
  LongParameterList:
    active: true
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
  NestedBlockDepth:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
  TooManyFunctions:
    active: true

coroutines:
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true

empty-blocks:
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  TooGenericExceptionThrown:
    active: true
  TooGenericExceptionCaught:
    active: true

naming:
  BooleanPropertyNaming:
    active: true
  ClassNaming:
    active: true
  ConstructorParameterNaming:
    active: true
  EnumNaming:
    active: true
  FunctionMaxLength:
    active: true
  FunctionParameterNaming:
    active: true
  InvalidPackageDeclaration:
    active: true
  LambdaParameterNaming:
    active: true
  MatchingDeclarationName:
    active: true
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  TopLevelPropertyNaming:
    active: true
  VariableMaxLength:
    active: true
  VariableNaming:
    active: true

style:
  UnusedImports:
    active: true
  WildcardImport:
    active: true
    excludeImports:
      - "kotlin.math.*"
